# Generated by Django 5.1.2 on 2024-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleme',
            name='CONSTRAINT',
            field=models.CharField(choices=[('arrival', "Date d'arrivée"), ('delivery', 'Date de livraison'), ('prep_time', 'Temps de préparation')], default='arrival', max_length=20),
            preserve_default=False,
        ),
    ]
