# Generated by Django 5.1.2 on 2024-11-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_rename_number_job_job_id_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmachine',
            name='ID_machine',
        ),
    ]
