# Generated by Django 5.1.2 on 2024-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_jobmachine_id_machine_alter_job_id_job_alter_job_d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('FIFO', 'FIFO (First In, First Out)'), ('LIFO', 'LIFO (Last In, First Out)'), ('SPT', 'SPT (Shortest Processing Time)'), ('EDD', 'EDD (Earliest Due Date)'), ('LPT', 'LPT (Longest Processing Time)')], default='FIFO', max_length=4, verbose_name='Règle de planification')),
                ('date_choisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de la sélection de la règle')),
            ],
        ),
    ]
