# Generated by Django 5.1.2 on 2024-11-13 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_planification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('SPT', 'SPT'), ('LPT', 'LPT'), ('None', 'Aucune contrainte')], max_length=10)),
                ('constraint', models.CharField(choices=[('No_wait', 'No wait'), ('No_idle', 'No idle'), ('None', 'Aucune contrainte')], default='None', max_length=20)),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Planification',
        ),
    ]
