# Generated by Django 5.1.2 on 2024-11-13 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_planningoption_delete_planification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_option', models.CharField(choices=[('FIFO', 'First In First Out'), ('LIFO', 'Last In First Out'), ('SPT', 'Shortest Processing Time'), ('LPT', 'Longest Processing Time')], max_length=10)),
                ('constraint_option', models.CharField(choices=[('NONE', 'Aucune contrainte'), ('SDST', 'Sequence Dependent Setup Time'), ('SIST', 'Sequence Independent Setup Time'), ('NO_WAIT', 'No Wait'), ('NO_IDLE', 'No Idle')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
