# Generated by Django 5.1.2 on 2024-11-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_planningchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('NONE', 'Aucune contrainte'), ('SDST', 'SDST'), ('SIST', 'SIST'), ('NO_WAIT', 'No wait'), ('NO_IDLE', 'No idle')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='planningoption',
            old_name='date_selected',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='planningoption',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='planningoption',
            name='user',
        ),
        migrations.AlterField(
            model_name='planningoption',
            name='option',
            field=models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('SPT', 'SPT'), ('LPT', 'LPT')], max_length=10),
        ),
        migrations.DeleteModel(
            name='PlanningChoice',
        ),
    ]
