# Generated by Django 5.1.2 on 2024-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_probleme_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='session_id',
            field=models.CharField(default=1, max_length=255, verbose_name='ID de la session'),
            preserve_default=False,
        ),
    ]
