# Generated by Django 5.1.2 on 2024-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_contraint_session_id_planningoption_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contraint',
        ),
        migrations.RemoveField(
            model_name='jobmachine',
            name='job',
        ),
        migrations.DeleteModel(
            name='PlanningOption',
        ),
        migrations.DeleteModel(
            name='Probleme',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobMachine',
        ),
    ]
